## 텍스트 임베딩하기

In [1]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma

C:\Users\joyce\AppData\Local\Temp\ipykernel_35348\3828565490.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import TextLoader

In [2]:
from dotenv import load_dotenv
load_dotenv()

True

In [3]:
import pandas as pd
books=pd.read_csv("books_cleaned.csv")

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [5]:
books['tagged_description']

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: str

일반 text match하는ㄴ것보다 isbn으로 연결하는게 더 깔끔함.

In [7]:
books["tagged_description"].to_csv(
    "tagged_description.txt",
    index=False,
    header=False
)

In [12]:
raw_documents=TextLoader("tagged_description.txt",encoding="utf-8").load()
text_splitter=CharacterTextSplitter(chunk_size=10000,chunk_overlap=0,separator="\n")#separator기준으로 split하도록
documents=text_splitter.split_documents(raw_documents)

In [13]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."\n"9780002261982 A new \'Christie for Christmas\' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. \'Supposing I were to come down one morning and find a dead body in the library, what should I do?\' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER\'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI"\n"9780006178736 A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia\'s schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power."\n"9780006280897 Lewis\' work on the nature of love divides love into four categories; Affection, Friendship, Eros and Charity. The first three come naturally to humanity. Charity, however, the Gift-love of God, is divine, and without this supernatural love, the natural loves become distorted and even dangerous."\n"9780006280934 ""In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors and thinkers, examines a universally applicable question within the human condition: If God is good and all-powerful, why does he allow his creatures to suffer pain? With his signature wealth of compassion and insight, C.S. Lewis offers answers to these crucial questions and shares his hope and wisdom to help heal a world hungering for a true understanding of human nature.""--Amazon."\n"9780006380832 Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall\'s history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition."\n"9780006470229 A new-cover reissue of the fourth book in the bestselling five-volume sf series created by the world-famous author of the Thomas Covenant chronicles -- and acclaimed as the \'best work of his career\'. Events were not moving as the Amnion had intended. Once again humans had been false in their dealings with the aliens. As the planetoid Thanatos Minor exploded into atoms, the Trumpet hurtled into space only one step ahead of hostile pursuers. On board were Morn Hyland and her force-grown son Davies, cyborg Angus Thermopyle and Captain Nick Succorso -- old enemies thrown together in a desperate bid for survival. For both the Amnion and the UMCP, the immediate capture of the fleeing ship and the secrets it contained was imperative. But for Trumpet\'s exhausted crew the only hope lay in an illegal lab in the distant binary solar system of Valdor Industrial. It would be a journey of unpredictable danger -- from which not all would return..."\n9780006472612 Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.\n"9780006482079 Tricked once more by his wily half-brother, Lysaer, Lord of Light, arrives at the tiny harbor town of Merior to find that Arithon\'s ship yards have been abandoned and meticulously destroyed, and that the Master of Shadow has disappeared as if into thin air. Meanwhile Arithon and the Mad Prophet Dakar are traveling on foot through the treacherous Kelhorn Mountains towards the Vastmark clans, there to raise further support for his cause. But raising a warhost is a costly business. Is it mere coincidence that Princess Talith—Lysaer\'s beautiful, headstrong wife—is taken captive and held for a vast ransom by a master brigand? The forces of light and shadow circle and feint, drawing ever closer to a huge conflict. And in the background the Fellowship of Seven Sorcerers and the Koriani Enchantresses watch and plan, and wait."\n"9780006483014 An omnibus volume of the author\'s complete story of the Arthurian epic which includes: ""The sword in the stone"" (1939), ""The witch in the wood"" (1939), ""The ill-made knight"" (1940), ""The candle in the wind"" (published for the first time), and ""The book of Merlyn."" 1996."\n"9780006483892 Available in the U.S. for the first time, this is the second volume in the exceptional Legends of the Riftwar series from ""New York Times""-bestselling authors Feist and Rosenberg."\n"9780006483908 Jimmy the Hand, boy thief of Krondor, lived in the shadows of the city. Though gifted beyond his peers, Jimmy is merely a pickpocket with potential--until he aids Prince Arutha in the rescue of Princess Anita from Duke Guy du Bas-Tyra, and runs afoul of ""Black Guy\'s"" secret police. Facing a choice between disappearing on his own or in a weighted barrel at the bottom of Krondor\'s harbor, Jimmy chooses the former. Forced to flee the only home he\'s ever known, Jimmy finds himself among the unsuspecting rural villagers of Land\'s End, where he hopes to prosper with his talents for con and thievery. But Land\'s End is home to many who tread the crooked path--and to a dark, dangerous presence even the local smugglers don\'t recognize. And suddenly Jimmy\'s youthful bravado and courage are leading him into the maw of chaos . . . and, quite possibly, to his doom."\n"9780006486145 Gareth is just a frightened young lad when he is drafted in to be the whipping-boy for the unruly Prince Dagnarus. Yet as they grow to be men, an unshakable bond is formed. And it is their destiny for them to become the two most powerful - and feared - men in the kingdom. But when Dagnarus decides to become a knight himself, he begins a chain of evil events that threaten to destroy the entire kingdom. Only by uniting the Sovereign Stone can peace be restored, and it is up to Dagnarus\' brother Helmos to try to achieve this impossible task, using his father\'s soldiers against his brother\'s army. All the while, Gareth is gaining mastery over the sinister Void magic, and he is devoted to helping his childhood companion.. This gripping story of magical power and corruption takes the unique viewpoint of focusing on the evil characters, as we follow them from boys to men. Filled with action, suspense and wonderfully imaginative characters, Water From the Well of Darkness is set to elevate the careers of bestselling authors Weis & Hickman to spectacular new heights."\n"9780006490456 Newly-Jacketed Edition Designed To Celebrate The 50Th Anniversary Of Christie S Faultlessly Plotted Witness For The Prosecution And Other Outstanding Plays. The Perfect Complement To The Latest Edition Of The Mousetrap And Selected Plays (50Th Aniversary Edition). Headlining This Book Is Witness For The Prosecution Christie S Highly Successful Stage Play Which Won The New York Drama Critics Circle Award For Best Foreign Play. A Stunning Courtroom Drama, It Tells The Story Of A Scheming Wife Testifying Against Her Husband In A Shocking Murder Trial. The Wild Beauty Of A Seaside House Perched High On The Devonshire River Tern Provides A Stunning Back-Drop In Towards Zero As A Psychopathic Murderer Homes In On The Unsuspecting Victims. Passion, Murder And Love Are The Deadly Ingredients In Verdict, Making It One Of Christie S More Unusual Thrillers And Prompting Her To Label It The Best Play I Have Written With The Exception Of Witness For The Prosecution . Go Back For Murder Tells The Story Of The Young And Feisty Carla Who, Orphaned At The Tender Age Of Five, Discovers Her Mother Was Imprisioned For Murdering Her Father And Determines To Prove Her Innocence."')

In [26]:
db_books=Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings()
)

In [27]:
query="A book to teach children about nature"
docs=db_books.similarity_search(query,k=10)

In [28]:
docs

[Document(id='17f51181-6859-4bab-974b-010af54a98df', metadata={'source': 'tagged_description.txt'}, page_content='"9780061205699 At the age of eight, Scout Finch is an entrenched free-thinker. She can accept her father\'s warning that it is a sin to kill a mockingbird, because mockingbirds harm no one and give great pleasure. The benefits said to be gained from going to school and keeping her temper elude her. The place of this enchanting, intensely moving story is Maycomb, Alabama. The time is the Depression, but Scout and her brother, Jem, are seldom depressed. They have appalling gifts for entertaining themselves—appalling, that is, to almost everyone except their wise lawyer father, Atticus. Atticus is a man of unfaltering good will and humor, and partly because of this, the children become involved in some disturbing adult mysteries: fascinating Boo Radley, who never leaves his house; the terrible temper of Mrs. Dubose down the street; the fine distinctions that make the Finch family ""quality""; the forces that cause the people of Maycomb to show compassion in one crisis and unreasoning cruelty in another. Also because Atticus is what he is, and because he lives where he does, he and his children are plunged into a conflict that indelibly marks their lives—and gives Scout some basis for thinking she knows just about as much about the world as she needs to."\n9780061208492 Seven Spiritual Masterworks by C. S. Lewis This classic collection includes C. S. Lewis\'s most important spiritual works: Mere Christianity The Screwtape Letters The Great Divorce The Problem of Pain Miracles A Grief Observed The Abolition of Man\n"9780061238239 A conclusion to the Earth Chronicles series brings the author\'s theories about the Anunnaki extraterrestrial beings full circle, addressing key questions pertaining to such topics as the biblical Daniel, Sir Isaac Newton, and the end of the world."\n"9780061312113 These works, as the sub-title makes clear, are unfinished sketches for Philosophical Investigations, possibly the most important and influential philosophical work of modern times. The \'Blue Book\' is a set of notes dictated to Witgenstein\'s Cambridge students in 1933-1934: the \'Brown Book\' was a draft for what eventually became the growth of the first part of Philosophical Investigations. This book reveals the germination and growth of the ideas which found their final expression in Witgenstein\'s later work. It is indispensable therefore to students of Witgenstein\'s thought and to all those who wish to study at first-hand the mental processes of a thinker who fundamentally changed the course of modern philosophy."\n9780062508867 This vivid and detailed biography strips away centuries of distortion and myth and presents a balanced view of the man whose religion continues to dramatically affect the course of history.\n9780062511119 The essence of perennial Stoic wisdom in aphorisms of stunning insight and simplicity. The West\'s first and best little instruction book offers thoroughly contemporary and pragmatic reflections on how best to live with serenity and joy.\n"9780062512796 Previously published as The Diary of a Magus, this book tells of Coelho\'s initiation into a spiritual path, leading to inner development and wisdom. He shares exercises in self-control and self-discovery, which he was taught on his pilgrimage along the ancient road to Santiago."\n"9780062513342 A Magical Tale About Forgiving Our Past and Believing in Our Future The enchanting, true story of The Valkyries begins in Rio de Janeiro when author Paulo Coelho gives his mysterious master J., the only manuscript for his book The Alchemist. Haunted by a devastating curse, Coelho confesses to J., ""I′ve seen my dreams fall apart just when I seemed about to achieve them."" In response, J. gives Coelho a daunting task: He must find and speak with his guardian angel. ""The curse can be broken,"" he replies, ""if you complete the task."" Rising to the challenge, Paulo and his wife, Cristina, drop everything, pack their bags, and take off on a forty day adventure into the starkly beautiful and sometimes dangerous Mojave Desert where they encounter more than they bargained for. A masterful blend of the exotic locales, dramatic adventure, and magical storytelling, for which Coelho′s fictional works are renowned, this true-life account is at once a modern-day adventure and a metaphysical odyssey."\n"9780062516374 Rainforest Healing from Your Home and Garden Find alternatives to chemical anti-depressants and painkillers in your spice rack. Learn about natural anti-itch salves for insect bites. Soothe and relieve envy, grief, sadness, and fear the Maya way. Rid your house of negative energy with a Maya cleansing ritual. Try the easy-to-make bronchitis remedy."\n"9780062700254 A beautiful gift edition of Thomas Bulfinch\'s classic retelling of famous myths and folk legends, with interpretive essays by Princeton classics professor Richard P. Martin."\n"9780064400961 Best Friends Forever There are lots of children on Hill Street, but no little girls Betsy\'s age. So when a new family moves into the house across the street, Betsy hopes they will have a little girl she can play with. Sure enough, they do—a little girl named Tacy. And from the moment they meet at Betsy\'s fifth birthday party, Betsy and Tacy becoms such good friends that everyone starts to think of them as one person—Betsy-Tacy. Betsy and Tacy have lots of fun together. They make a playhouse from a piano box, have a sand store, and dress up and go calling. And one day, they come home to a wonderful surprise—a new friend named Tib. Ever since their first publication in the 1940\'s, the Betsy-Tacy stories have been loved by each generation of young readers."\n"9780064400992 Betsy, Tacy, and Tib can\'t wait to be ten. After all, getting two numbers in your age is the beginning of growing up—exciting things are bound to happen. And they do! The girls fall in love with the King of Spain, perform in the School Entertainment, and for the first time, go all the way over the Big Hill to Little Syria by themselves. There Betsy, Tacy, and Tib make new friends and learn a thing or two. They learn that new Americans are sometimes the best Americans. And they learn that they themselves wouldn\'t want to be anything else. Ever since their first publication in the 1940s, the Betsy-Tacy stories have been loved by each generation of young readers."\n"9780064401685 When a strange little man comes to the Coven Tree Church Social promising he can give people exactly what they ask for, three young believers-in-magic each make a wish that comes true in the most unexpected way."\n"9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author\'s father].\' \'BL. 1986 Children\'s Editors\' Choices (BL) Children\'s Choices for 1987 (IRA/CBC) Notable 1986 Childrens\' Trade Books in Social Studies (NCSS/CBC) 1986 Children\'s Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"\n"9780064403368 Twelve-year-old Casey is waiting for the day that Barney, her father, hits it big -- \'cause when that horse comes in, he tells her, it\'s the penthouse suite. But then hr ends up in the hospital, and Casey is sent to Chinatown to live with her grandmother, Paw-Paw. Now the waiting seems longer than ever. Casey feels lost in Chinatown. She\'s not prepared for the Chinese school, the noisy crowds, missing her father. But Paw-Paw tells her about the mother Casey never knew, and about her family\'s owl charm and her true Chinese name. And Casey at last begins to understand that this -- Paw-Paw\'s Chinatown home, her parents\' home -- is her home,too."\n"9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"\n"9780064404419 ""Culled from 69 stories collected in a [1930s] WPA project, [these 20] tales are organized into sections with themes like \'Tricksters\' or \'Virtues and Vices,\' each with a thoughtful introduction placing the individual stories in the context of feelings and background of the original tellers. Yep\'s telling is vigorous, often poetic, imbued with earthy humor and realism touched with fatalism. A handsomely designed collection."" —K. Notable Children\'s Books of 1989 (ALA) The USA Through Children\'s Books 1990 (ALA) 1989 Boston Globe–Horn Book Award for Nonfiction 1990 Fanfare Honor List (The Horn Book) 1989 Children\'s Editors\' Choices (BL) Notable 1989 Children\'s Trade Books in Social Studies (NCSS/CBC) Children\'s Books of 1989 (Library of Congress) 1989 Children\'s Books (NY Public Library) ""The Best Books"" 1989 (Parents Magazine)"\n"9780064404891 In 1867, Otter travels from Three Willows Village in China to California -- the Land of the Golden Mountain. There he will join his father and uncle. In spite of the presence of family, Otter is a stranger among the other Chinese in this new land. And where he expected to see a land of goldfields, he sees only vast, cold whiteness. But Otter\'s dream is to learn all he can, take the technology back to the Middle Kingdom, and free China from the Manchu invaders. Otter and the others board a machine that will change his life -- a train for which he would open the Dragon\'s Gate."'),

지금은 description만 반환-> 우리는 책 정보를 알고싶은데

In [29]:
books[books["isbn13"] == int(
    docs[0].page_content.split()[0].strip('"')
)]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description
391,9780061205699,0061205699,To Kill a Mockingbird (slipcased edition),Harper Lee,Fiction,http://books.google.com/books/content?id=M9lKH...,"At the age of eight, Scout Finch is an entrenc...",2006.0,4.27,323.0,250.0,0,To Kill a Mockingbird (slipcased edition),"9780061205699 At the age of eight, Scout Finch..."

In [33]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int=10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)
    books_list = []
    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]
    return books[books["isbn13"].isin(books_list)].head(top_k)

In [34]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description
114,9780060509057,0060509058,Travels,Michael Crichton,Biography & Autobiography,http://books.google.com/books/content?id=QYilZ...,Often I feel I go to some distant region of th...,2002.0,3.95,400.0,6812.0,0,Travels,9780060509057 Often I feel I go to some distan...
260,9780060852559,0060852550,"Animal, Vegetable, Miracle",Barbara Kingsolver;Camille Kingsolver;Steven L...,Biography & Autobiography,http://books.google.com/books/content?id=qLkEY...,Bestselling author Barbara Kingsolver returns ...,2007.0,4.04,370.0,86130.0,0,"Animal, Vegetable, Miracle: A Year of Food Life",9780060852559 Bestselling author Barbara Kings...
306,9780060932664,006093266X,Collected Novellas,Gabriel Garcia Marquez,Fiction,http://books.google.com/books/content?id=JRcVu...,"Renowned as a master of magical realism, Gabri...",1999.0,4.01,288.0,822.0,0,Collected Novellas,9780060932664 Renowned as a master of magical ...
391,9780061205699,0061205699,To Kill a Mockingbird (slipcased edition),Harper Lee,Fiction,http://books.google.com/books/content?id=M9lKH...,"At the age of eight, Scout Finch is an entrenc...",2006.0,4.27,323.0,250.0,0,To Kill a Mockingbird (slipcased edition),"9780061205699 At the age of eight, Scout Finch..."
442,9780067575208,006757520X,The Sense of Wonder,Rachel Carson,Nature,http://books.google.com/books/content?id=Zee5S...,"First published more than three decades ago, t...",1998.0,4.39,112.0,1160.0,0,The Sense of Wonder,9780067575208 First published more than three ...
690,9780140447897,014044789X,Metamorphosis,Ovid;David Raeburn,Fiction,http://books.google.com/books/content?id=D3McX...,A new translation in hexameter verse of Ovid's...,2004.0,4.05,723.0,46550.0,0,Metamorphosis,9780140447897 A new translation in hexameter v...
880,9780152049676,0152049673,Winter is the Warmest Season,Lauren Stringer,Juvenile Fiction,http://books.google.com/books/content?id=S1EOm...,A child describes pleasant ways to stay warm d...,2006.0,3.91,40.0,360.0,0,Winter is the Warmest Season,9780152049676 A child describes pleasant ways ...
1733,9780375760136,037576013X,Daniel Deronda,George Eliot,Fiction,http://books.google.com/books/content?id=uPiMx...,"Deronda, a high-minded young man searching for...",1876.0,3.83,796.0,19852.0,0,Daniel Deronda,"9780375760136 Deronda, a high-minded young man..."
1911,9780393320039,0393320030,On Becoming a Novelist,John Gardner,Language Arts & Disciplines,http://books.google.com/books/content?id=Go68K...,An indispensable reference for anyone who hope...,1999.0,4.11,150.0,2241.0,0,On Becoming a Novelist,9780393320039 An indispensable reference for a...
2215,9780440420637,0440420636,The Green Toenails Gang,Marjorie Weinman Sharmat,Juvenile Fiction,http://books.google.com/books/content?id=yP1lc...,"Wealthy Olivia Sharp, agent for secrets, uncov...",2005.0,3.74,72.0,41.0,0,The Green Toenails Gang,"9780440420637 Wealthy Olivia Sharp, agent for ..."