## 더 정교한 추천을 위해 책 장르 분류하기-using zero-shot LLM classification

In [2]:
!pip install transformers torch tqdm pandas numpy

Requirement already satisfied: transformers in /usr/local/lib/python3.13/dist-packages (5.16.1)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (2.11.0+cu128)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (1.28.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.23.1)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch) (3.32.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch) (1.7.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
from sympy import sequence

books=pd.read_csv("/content/drive/MyDrive/uni/Study/book-recommendation/books_cleaned.csv")

In [5]:
books["categories"].value_counts().reset_index()

                     categories  count
0                       Fiction   2111
1              Juvenile Fiction    390
2     Biography & Autobiography    311
3                       History    207
4            Literary Criticism    124
..                          ...    ...
474  Human-animal relationships      1
475                 Imperialism      1
476                  Aged women      1
477            Humorous stories      1
478                     Butlers      1

[479 rows x 2 columns]

In [6]:
books["categories"].value_counts().reset_index().query("count>50")

                   categories  count
0                     Fiction   2111
1            Juvenile Fiction    390
2   Biography & Autobiography    311
3                     History    207
4          Literary Criticism    124
5                    Religion    117
6                  Philosophy    117
7     Comics & Graphic Novels    116
8                       Drama     86
9         Juvenile Nonfiction     57
10                    Science     56
11                     Poetry     51

In [7]:
books[books["categories"]=="Juvenile Fiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,0,Ocean Star Express,9780006646006 Joe and his parents are enjoying...
79,9780020442608,0020442602,The voyage of the Dawn Treader,Clive Staples Lewis,Juvenile Fiction,http://books.google.com/books/content?id=fDD3C...,"The ""Dawn Treader"" is the first ship Narnia ha...",1970.0,4.09,216.0,2869.0,0,The voyage of the Dawn Treader,"9780020442608 The ""Dawn Treader"" is the first ..."
85,9780030547744,0030547741,Where the Red Fern Grows,Wilson Rawls,Juvenile Fiction,http://books.google.com/books/content?id=IHpRw...,A young boy living in the Ozarks achieves his ...,2000.0,4.37,288.0,95.0,0,Where the Red Fern Grows: The Story of Two Dog...,9780030547744 A young boy living in the Ozarks...
86,9780060000141,0060000147,Poppy's Return,Avi,Juvenile Fiction,http://books.google.com/books/content?id=XbcMJ...,"There's trouble at Gray House, the girlhood ho...",2006.0,3.99,256.0,1086.0,0,Poppy's Return,"9780060000141 There's trouble at Gray House, t..."
87,9780060001537,0060001534,Diary of a Spider,Doreen Cronin,Juvenile Fiction,http://books.google.com/books/content?id=UWvZo...,This is the diary ... of a spider. But don't b...,2005.0,4.25,40.0,7903.0,0,Diary of a Spider,9780060001537 This is the diary ... of a spide...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4845,9781590385814,1590385810,Fablehaven,Brandon Mull,Juvenile Fiction,http://books.google.com/books/content?id=tbVIP...,When Kendra and Seth go to stay at their grand...,2006.0,4.09,351.0,111896.0,0,Fablehaven,9781590385814 When Kendra and Seth go to stay ...
4930,9781596792500,1596792507,Sherlock Holmes and the Case of the Hound of t...,Arthur Conan Doyle;Malvina G. Vogel,Juvenile Fiction,http://books.google.com/books/content?id=EWgWP...,Sherlock Holmes and Dr. Watson travel to the b...,2005.0,4.51,237.0,28.0,0,Sherlock Holmes and the Case of the Hound of t...,9781596792500 Sherlock Holmes and Dr. Watson t...
4942,9781599900056,159990005X,The Drift House,Dale Peck,Juvenile Fiction,http://books.google.com/books/content?id=kbwPY...,Sent to stay with their uncle in a ship-like h...,2006.0,3.64,437.0,595.0,0,The Drift House: The First Voyage,9781599900056 Sent to stay with their uncle in...
5010,9781844580514,1844580512,Attack of the Jaguar,M. A. Harvey,Juvenile Fiction,http://books.google.com/books/content?id=3HUdt...,This training manual for operatives of Xtreme ...,2004.0,3.40,125.0,4.0,0,Attack of the Jaguar,9781844580514 This training manual for operati...
5157,9781932416374,1932416374,The Very Persistent Gappers of Frip,George Saunders;Lane Smith,Juvenile Fiction,http://books.google.com/books/content?id=xYJOP...,A novel set in the seaside village of Frip fol...,2006.0,4.11,84.0,2317.0,0,The Very Persistent Gappers of Frip,9781932416374 A novel set in the seaside villa...

In [8]:
books[books["categories"]=="Juvenile Nonfiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description
107,9780060277406,0060277408,The Secret Garden Cookbook,Amy Cotler,Juvenile Nonfiction,http://books.google.com/books/content?id=c7E_H...,Frances Hodgson Burnett's The Secret Garden de...,1999.0,4.28,128.0,142.0,0,The Secret Garden Cookbook: Recipes Inspired b...,9780060277406 Frances Hodgson Burnett's The Se...
108,9780060278427,0060278420,Laura's Album,William Anderson,Juvenile Nonfiction,http://books.google.com/books/content?id=_zTkq...,Though best known as the author of the Little ...,1998.0,4.30,80.0,713.0,0,Laura's Album: A Remembrance Scrapbook of Laur...,9780060278427 Though best known as the author ...
228,9780060782139,0060782137,Time For Kids: Butterflies!,Editors of TIME For Kids,Juvenile Nonfiction,http://books.google.com/books/content?id=OdZxn...,"Butterflies There are 20,000 different kinds o...",2006.0,4.00,32.0,20.0,0,Time For Kids: Butterflies!,"9780060782139 Butterflies There are 20,000 dif..."
267,9780060882600,0060882603,The Annotated Charlotte's Web,E. B. White,Juvenile Nonfiction,http://books.google.com/books/content?id=vaYYH...,"Charlotte's Web, one of America's best-loved c...",2006.0,4.16,320.0,41.0,0,The Annotated Charlotte's Web,"9780060882600 Charlotte's Web, one of America'..."
434,9780064462044,0064462048,My Little House Crafts Book,Carolyn Strom Collins,Juvenile Nonfiction,http://books.google.com/books/content?id=lTzrs...,Make the same pioneer crafts that Laura did! I...,1998.0,4.05,64.0,56.0,0,My Little House Crafts Book: 18 Projects from ...,9780064462044 Make the same pioneer crafts tha...
435,9780064462341,006446234X,Pioneer Girl,William Anderson,Juvenile Nonfiction,http://books.google.com/books/content?id=Sj4UD...,The pioneer spirit lives on... Readers around ...,2000.0,4.15,32.0,414.0,0,Pioneer Girl: The Story of Laura Ingalls Wilder,9780064462341 The pioneer spirit lives on... R...
439,9780066236179,0066236177,A Light in the Attic Book and CD,Shel Silverstein,Juvenile Nonfiction,http://books.google.com/books/content?id=FJfQs...,Last night while I lay thinking here Some What...,2001.0,4.34,176.0,590.0,0,A Light in the Attic Book and CD,9780066236179 Last night while I lay thinking ...
812,9780142302279,0142302279,Dirty Beasts,Roald Dahl,Juvenile Nonfiction,NaN,Poems tell the stories of a smart pig who outw...,2002.0,4.02,32.0,3953.0,0,Dirty Beasts,9780142302279 Poems tell the stories of a smar...
821,9780142407226,0142407224,The Tough Guide to Fantasyland,Diana Wynne Jones,Juvenile Nonfiction,http://books.google.com/books/content?id=v5jxA...,A unique guide to fantasy literature helps rea...,2006.0,3.94,234.0,3897.0,0,The Tough Guide to Fantasyland,9780142407226 A unique guide to fantasy litera...
823,9780142407929,0142407925,The BFG,Roald Dahl;David Wood;Jane Walmsley,Juvenile Nonfiction,http://books.google.com/books/content?id=aDf-O...,"With notes on staging, props, and costumes, a ...",2007.0,4.26,128.0,452.0,0,The BFG: A Set of Plays,"9780142407929 With notes on staging, props, an..."
1014,9780198320272,0198320272,Julius Caesar,William Shakespeare,Juvenile Nonfiction,http://books.google.com/books/content?id=Nlmkh...,Caesar returns from a triumphant battle to Rom...,2001.0,3.67,128.0,133575.0,0,Julius Caesar,9780198320272 Caesar returns from a triumphant...
1074,9780237525378,0237525372,Oliver Twist,Pauline Francis;Charles Dickens,Juvenile Nonfiction,http://books.google.com/books/content?id=X6RvT...,This wonderful series is a quick way into a ra...,2003.0,3.66,48.0,92.0,0,Oliver Twist,9780237525378 This wonderful series is a quick...
1739,9780375812934,0375812938,Jurassic Park Institute Dinosaur Field Guide,Thomas R. Holtz;M. K. Brett-Surman,Juvenile Nonfiction,http://books.google.com/books/content?id=vW3hm...,Discusses dinosaur research and what can be le...,2001.0,4.08,160.0,2.0,0,Jurassic Park Institute Dinosaur Field Guide,9780375812934 Discusses dinosaur research and ...
1742,9780375823787,0375823786,Ancient Greece and the Olympics,Mary Pope Osborne;Natalie Pope Boyce,Juvenile Nonfiction,http://books.google.com/books/content?id=5cPbW...,"Filled with fascinating facts, a Magic Tree Ho...",2004.0,4.06,119.0,1044.0,0,Ancient Greece and the Olympics: A Nonfiction ...,"9780375823787 Filled with fascinating facts, a..."
1770,9780380732548,0380732548,Anne Frank,Johanna Hurwitz,Juvenile Nonfiction,http://books.google.com/books/content?id=3ja19...,"From July 1942 until August 1944, a young girl...",1999.0,3.99,64.0,143.0,0,Anne Frank: Life in Hiding,9780380732548 From July 1942 until August 1944...
1972,9780395776087,0395776082,An American Plague,Jim Murphy,Juvenile Nonfiction,NaN,Recreates the devastation rendered to the city...,2003.0,3.80,165.0,3338.0,0,An American Plague: The True and Terrifying St...,9780395776087 Recreates the devastation render...
2105,9780439314558,0439314550,Conversations with J.K. Rowling,Lindsey Fraser,Juvenile Nonfiction,http://books.google.com/books/content?id=Ly8dl...,From her birth in Chipping Sodbury near Bristo...,2001.0,3.99,96.0,4184.0,0,Conversations with J.K. Rowling,9780439314558 From her birth in Chipping Sodbu...
2117,9780439420068,0439420067,Eat!,Roberta Grobel Intrater,Juvenile Nonfiction,http://books.google.com/books/content?id=BnQ2n...,A group of babies enjoys some favorite foods--...,2002.0,3.95,10.0,54.0,0,Eat!,9780439420068 A group of babies enjoys some fa...
2139,9780439736466,0439736463,"Where We Are, what We See",David Levithan,Juvenile Nonfiction,NaN,"A collection of poems, stories, essays, and ar...",2005.0,3.73,288.0,41.0,0,"Where We Are, what We See: The Best Young Arti...","9780439736466 A collection of poems, stories, ..."
2183,9780440229353,0440229359,How Angel Peterson Got His Name,Gary Paulsen,Juvenile Nonfiction,http://books.google.com/books/content?id=maJrL...,Author Gary Paulsen relates tales from his you...,2004.0,3.93,111.0,1139.0,0,How Angel Peterson Got His Name: And Other Out...,9780440229353 Author Gary Paulsen relates tale...
2211,9780440419174,0440419174,Vincent Van Gogh,Jan Greenberg;Sandra Jane Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=n7kv9...,Profiles the turbulent life of Vincent van Gog...,2003.0,3.95,144.0,209.0,0,Vincent Van Gogh: Portrait of an Artist,9780440419174 Profiles the turbulent life of V...
2320,9780448437439,0448437430,Who Was John F. Kennedy?,Yona Zeldis McDonough;Jill Weber,Juvenile Nonfiction,http://books.google.com/books/content?id=qjCzJ...,Chronicles the life of the president who saw A...,2004.0,4.19,112.0,598.0,0,Who Was John F. Kennedy?,9780448437439 Chronicles the life of the presi...
2323,9780448444826,0448444828,Who Was Anne Frank?,Ann Abramson,Juvenile Nonfiction,http://books.google.com/books/content?id=Bz37n...,Looks closely at Anne Frank's life before the ...,2007.0,4.26,103.0,1763.0,0,Who Was Anne Frank?,9780448444826 Looks closely at Anne Frank's li...
2503,9780486276809,0486276805,The Secret Garden Coloring Book,Frances Hodgson Burnett,Juvenile Nonfiction,http://books.google.com/books/content?id=sxHdA...,Ten-year-old Mary comes to live in a lonely ho...,2014.0,4.25,48.0,4.0,0,The Secret Garden Coloring Book,9780486276809 Ten-year-old Mary comes to live ...
2509,9780486296388,0486296385,Ballet Class Coloring Book,John Green;Caroline Denzler,Juvenile Nonfiction,http://books.google.com/books/content?id=p6PBk...,"Forty-two clear, accurate drawings (all in pro...",1997.0,3.64,48.0,11.0,0,Ballet Class Coloring Book,"9780486296388 Forty-two clear, accurate drawin..."
2609,9780521618748,0521618746,Hamlet,William Shakespeare,Juvenile Nonfiction,http://books.google.com/books/content?id=5m2UP...,This edition of Hamlet is part of the groundbr...,2005.0,4.01,289.0,577429.0,0,Hamlet,9780521618748 This edition of Hamlet is part o...
2615,9780525469780,0525469788,"Boy, Were We Wrong about Dinosaurs!",Kathleen V. Kudlinski,Juvenile Nonfiction,http://books.google.com/books/content?id=QrRKD...,"Examines what is known about dinosaur bones, b...",2005.0,3.93,32.0,243.0,0,"Boy, Were We Wrong about Dinosaurs!",9780525469780 Examines what is known about din...
2858,9780590032490,0590032496,The witches,Roald Dahl,Juvenile Nonfiction,http://books.google.com/books/content?id=tpQxo...,"A young boy and his Norwegian grandmother, who...",1997.0,4.17,208.0,254867.0,0,The witches,9780590032490 A young boy and his Norwegian gr...
2859,9780590103879,0590103873,Expository Writing,Tara McCarthy,Juvenile Nonfiction,http://books.google.com/books/content?id=9HKHF...,A Down-to-Earth Approach James Henslin shares ...,1998.0,4.33,88.0,3.0,0,Expository Writing,9780590103879 A Down-to-Earth Approach James H...
2897,9780618111206,0618111204,Once a Wolf,Stephen R. Swinburne;Jim Brandenburg,Juvenile Nonfiction,http://books.google.com/books/content?id=UkZWu...,With powerful and rare photos by a former phot...,2001.0,4.06,48.0,42.0,0,Once a Wolf: How Wildlife Biologists Fought to...,9780618111206 With powerful and rare photos by...
3133,9780679890522,0679890521,The Trail of Tears,Joseph Bruchac;Diana Magnuson,Juvenile Nonfiction,http://books.google.com/books/content?id=QxRUP...,"In 1838, settlers moving west forced the great...",1999.0,3.88,48.0,155.0,0,The Trail of Tears,"9780679890522 In 1838, settlers moving west fo..."
3202,9780689833762,0689833768,Sad Underwear and Other Complications,Judith Viorst,Juvenile Nonfiction,http://books.google.com/books/content?id=e-sEA...,"Knock, knock. Who's there? Someone with sad un...",2000.0,3.87,80.0,104.0,0,Sad Underwear and Other Complications: More Po...,"9780689833762 Knock, knock. Who's there? Someo..."
3203,9780689834196,0689834195,Salt in His Shoes,Deloris Jordan;Roslyn M. Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=hYzQw...,"Young Michael Jordan, who is smaller than the ...",2003.0,4.21,32.0,1054.0,0,Salt in His Shoes: Michael Jordan in Pursuit o...,"9780689834196 Young Michael Jordan, who is sma..."
3204,9780689835612,0689835612,Where Is Baby's Mommy?,Karen Katz,Juvenile Nonfiction,NaN,Is Mommy behind the chair? Is Mommy behind the...,2001.0,4.15,14.0,408.0,0,Where Is Baby's Mommy?: A Karen Katz Lift-the-...,9780689835612 Is Mommy behind the chair? Is Mo...
3219,9780689869907,0689869908,Beatrice's Goat,Page McBrier,Juvenile Nonfiction,http://books.google.com/books/content?id=4MNED...,In this story based on a case from Project Hei...,2004.0,4.24,40.0,523.0,0,Beatrice's Goat,9780689869907 In this story based on a case fr...
3223,9780689876707,068987670X,Star Bright,Cathy Hapka,Juvenile Nonfiction,http://books.google.com/books/content?id=JPuiC...,PopTV is going to follow Star around for twent...,2005.0,3.67,160.0,3.0,0,Star Bright,9780689876707 PopTV is going to follow Star ar...
3263,9780723247791,072324779X,The Tale of The Flopsy Bunnies,Beatrix Potter,Juvenile Nonfiction,http://books.google.com/books/content?id=D2uQt...,"This original, authorised version has been lov...",2010.0,4.19,58.0,5051.0,0,The Tale of The Flopsy Bunnies,"9780723247791 This original, authorised versio..."
3270,9780736805995,0736805990,"The Girlhood Diary of Louisa May Alcott, 1843-...",Louisa May Alcott,Juvenile Nonfiction,http://books.google.com/books/content?id=_dP35...,Excerpts from the girlhood diary of Louisa May...,2001.0,3.87,32.0,26.0,0,"The Girlhood Diary of Louisa May Alcott, 1843-...",9780736805995 Excerpts from the girlhood diary...
3292,9780739844328,0739844326,Bill Gates,Sara Barton-Wood,Juvenile Nonfiction,http://books.google.com/books/content?id=Fr814...,"Presents the life of Bill Gates, from his chil...",2001.0,5.00,48.0,0.0,0,Bill Gates: Computer Legend,"9780739844328 Presents the life of Bill Gates,..."
3522,9780753459645,0753459647,I Wonder Why the Sun Rises,Brenda Walpole,Juvenile Nonfiction,http://books.google.com/books/content?id=SqpYs...,What is a leap year? Why are bees busy in summ...,2006.0,3.95,32.0,50.0,0,I Wonder Why the Sun Rises: and Other Question...,9780753459645 What is a leap year? Why are bee...
3552,9780756614195,0756614198,Star Wars,Kristin Lund;Simon Beecroft;Kerrie Dougherty,Juvenile Nonfiction,http://books.google.com/books/content?id=PAq2A...,Glorious full-color illustrations create a sea...,2005.0,4.30,175.0,128.0,0,Star Wars: Complete Locations,9780756614195 Glorious full-color illustration...
3565,9780761417101,0761417109,The Star-Spangled Banner,Debra Hess,Juvenile Nonfiction,http://books.google.com/books/content?id=e-uzI...,Looks at the events leading up to the War of 1...,2003.0,4.00,40.0,1.0,0,The Star-Spangled Banner,9780761417101 Looks at the events leading up t...
3797,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,0,Tree,9780789458209 Photographs and text explore the...
3798,9780791070482,0791070484,Bram Stoker's Dracula,Harold Bloom,Juvenile Nonfiction,http://books.google.com/books/content?id=vQ6SQ...,Presents a collection of critical essays on Br...,2003.0,3.83,243.0,6.0,0,Bram Stoker's Dracula,9780791070482 Presents a collection of critica...
3799,9780791081266,0791081265,Edith Wharton's The Age of Innocence,Harold Bloom,Juvenile Nonfiction,http://books.google.com/books/content?id=MNuFk...,One of Edith Wharton's most critically acclaim...,2005.0,3.71,205.0,11.0,0,Edith Wharton's The Age of Innocence,9780791081266 One of Edith Wharton's most crit...
3800,9780792241737,0792241738,Freedom Riders,Ann Bausum,Juvenile Nonfiction,http://books.google.com/books/content?id=JIlhQ...,Offers the true account of two young men who t...,2006.0,3.97,80.0,247.0,0,Freedom Riders: John Lewis and Jim Zwerg on th...,9780792241737 Offers the true account of two y...
3861,9780805069853,0805069852,You Come Too,Robert Frost,Juvenile Nonfiction,http://books.google.com/books/content?id=gZWM6...,An introduction to Robert Frost features an ab...,2002.0,4.16,92.0,77.0,0,You Come Too: Favorite Poems for Readers of Al...,9780805069853 An introduction to Robert Frost ...
3863,9780805071061,0805071067,Rosa,Nikki Giovanni,Juvenile Nonfiction,http://books.google.com/books/content?id=3pulA...,Provides the story of the black woman whose re...,2005.0,4.35,40.0,5942.0,0,Rosa,9780805071061 Provides the story of the black ...
3921,9780810935204,0810935201,Lewis Carroll's Jabberwocky,Graeme Base,Juvenile Nonfiction,http://books.google.com/books/content?id=tyMFA...,Lewis Carroll's classic and inventive verse co...,1996.0,4.14,14.0,31.0,0,Lewis Carroll's Jabberwocky: A Book of Brillig...,9780810935204 Lewis Carroll's classic and inve...
4069,9780822560562,0822560569,Barack Obama,Marlene Targ Brill,Juvenile Nonfiction,http://books.google.com/books/content?id=FIhyP...,Chronicles the life and career of the communit...,2006.0,3.96,48.0,19.0,0,Barack Obama: Working to Make a Difference,9780822560562 Chronicles the life and career o...
4072,9780823410781,0823410781,A Picture Book of Anne Frank,NaN,Juvenile Nonfiction,http://books.google.com/books/content?id=CSNxW...,Traces the life of the young Jewish girl whose...,1993.0,4.17,32.0,208.0,0,A Picture Book of Anne Frank,9780823410781 Traces the life of the young Jew...
4409,9781400307845,1400307848,Writings to Young Women from Laura Ingalls Wil...,Laura Ingalls Wilder;Stephen W. Hines,Juvenile Nonfiction,http://books.google.com/books/content?id=e5gSD...,Using selections from her works and memoirs of...,2006.0,3.95,113.0,100.0,0,Writings to Young Women from Laura Ingalls Wil...,9781400307845 Using selections from her works ...
4596,9781560067849,1560067845,Flowers for Algernon,Patrice Cassedy,Juvenile Nonfiction,http://books.google.com/books/content?id=x_CUf...,"Discusses the young adult book ""Flowers for Al...",2000.0,3.00,96.0,1.0,0,Flowers for Algernon,"9781560067849 Discusses the young adult book ""..."
4744,9781580495868,1580495869,The Red Badge of Courage,Stephen Crane,Juvenile Nonfiction,http://books.google.com/books/content?id=lN1ga...,As he faces battle in the Civil War for the fi...,2004.0,3.23,170.0,74477.0,0,The Red Badge of Courage,9781580495868 As he faces battle in the Civil ...
4808,9781586853334,1586853333,The Big Book of Boy Stuff,Bart King,Juvenile Nonfiction,http://books.google.com/books/content?id=08Ilm...,There's this boy. Let's say he's somewhere bet...,2004.0,4.24,292.0,141.0,0,The Big Book of Boy Stuff,9781586853334 There's this boy. Let's say he's...
5041,9781857232097,1857232097,The Fires of Heaven,Robert Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=4HyfQ...,The fifth book in Robert Jordan's internationa...,1994.0,4.15,912.0,106302.0,0,The Fires of Heaven,9781857232097 The fifth book in Robert Jordan'...
5142,9781931414166,1931414165,The Brooklyn Bridge,Elizabeth Mann;Alan Witschonke,Juvenile Nonfiction,http://books.google.com/books/content?id=s28MA...,Describes the construction of the Brooklyn Bri...,2006.0,4.44,46.0,35.0,0,The Brooklyn Bridge,9781931414166 Describes the construction of th...

In [9]:
category_mapping={'Fiction':"fiction",
                  'Juvenile Fiction':"children's fiction",
                  'Biography & Autobiography': "nonfiction",
                  'History':"nonfiction",
                  'Religion':"nonfiction",
                  'Comics & Graphic Novels':"fiction",
                  'Drama':"fiction",
                  'Juvenile Nonfiction':"children's nonfiction",
                  'Science':"nonfiction",
                  'Poetry':"fiction"}
books["simple_categories"]=books["categories"].map(category_mapping)

In [10]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,0,Journey to the East,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,NaN
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,NaN
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,nonfiction

In [11]:
books.loc[~books["categories"].isin(category_mapping.keys()), "categories"].value_counts()

categories
Literary Criticism      124
Philosophy              117
Literary Collections     50
Business & Economics     49
Social Science           48
                       ...
Autism                    1
Botanique                 1
Antiheroes                1
English essays            1
Theology, Doctrinal       1
Name: count, Length: 469, dtype: int64

In [12]:
category_mapping = {
    'Fiction': "fiction",
    'Juvenile Fiction': "children's fiction",
    'Biography & Autobiography': "nonfiction",
    'History': "nonfiction",
    'Religion': "nonfiction",
    'Comics & Graphic Novels': "fiction",
    'Drama': "fiction",
    'Juvenile Nonfiction': "children's nonfiction",
    'Science': "nonfiction",
    'Poetry': "fiction",


}

books["simple_categories"] = books["categories"].map(category_mapping)

In [13]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,0,Journey to the East,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,NaN
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,NaN
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,nonfiction

In [14]:
books[~(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,0,Warhost of Vastmark,9780006482079 Tricked once more by his wily ha...,fiction
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,0,Ocean Star Express,9780006646006 Joe and his parents are enjoying...,children's fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,0,Taken at the Flood,9780007121014 A Few Weeks After Marrying An At...,fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5174,9781933372198,1933372192,Amazing Disgrace,James Hamilton-Paterson,Fiction,http://books.google.com/books/content?id=s7jyA...,In this sequel to the popular Cooking with Fer...,2006.0,3.79,320.0,219.0,0,Amazing Disgrace,9781933372198 In this sequel to the popular Co...,fiction
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,"""Cornell Woolrich's novels define the essence ...",2007.0,3.77,344.0,680.0,0,Night Has a Thousand Eyes,"9781933648279 ""Cornell Woolrich's novels defin...",fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,0,Coin Locker Babies,9784770028969 Rescued from the lockers in whic...,fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,fiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,nonfiction

### zero-shot

In [15]:
from transformers import pipeline
fiction_categories=["fiction","nonfiction"]
pipe=pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=0 )

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [16]:
sequence= books.loc[books["simple_categories"]=="fiction","description"].reset_index(drop=True)[0]

In [17]:
pipe(sequence, fiction_categories)

{'sequence': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'labels': ['fiction', 'nonfiction'],
 'scores': [0.8951419591903687, 0.10485801845788956]}

fiction일 확률이 0.895로 나름 정확하게 필터링됨.

In [18]:
import numpy as np
#가능성 높은 인덱스 반환
max_index=np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label=pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'fiction'

In [19]:
def generate_predictions(sequence,categories):
    predictions=pipe(sequence, categories)
    max_index=np.argmax(predictions["scores"])
    max_label=predictions["labels"][max_index]
    return max_label

In [20]:
import torch

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.11.0+cu128
12.8
True

In [21]:
#how good is this model?
from tqdm import tqdm
actual_cats=[]
predicted_cats=[]
for i in tqdm(range(0,300)):
    sequence=books.loc[books["simple_categories"]=="fiction","description"].reset_index(drop=True)[i]
    predicted_cats+=[generate_predictions(sequence,fiction_categories)]
    actual_cats+=["fiction"]

  2%|▏         | 7/300 [00:01<00:54,  5.38it/s][transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
100%|██████████| 300/300 [00:33<00:00,  9.01it/s]

In [22]:
for i in tqdm(range(0,300)):
    sequence=books.loc[books["simple_categories"]=="nonfiction","description"].reset_index(drop=True)[i]
    predicted_cats+=[generate_predictions(sequence,fiction_categories)]
    actual_cats+=["nonfiction"]

100%|██████████| 300/300 [00:26<00:00, 11.31it/s]

In [23]:
predictions_df=pd.DataFrame({"actual_categories":actual_cats, "predicted_categories":predicted_cats})

In [24]:
predictions_df["correct_prediction"]=np.where(predictions_df["actual_categories"]==predictions_df["predicted_categories"],1,0)

In [25]:
predictions_df["correct_prediction"].sum()/len(predictions_df)

np.float64(0.69)

fiction/nonfiction label안된 행들 처리하기

In [26]:
isbns=[]
predicted_cats=[]
missing_cats=books.loc[books["simple_categories"].isna(), ["isbn13","description"]].reset_index(drop=True)

In [27]:
print(len(missing_cats))

1695

In [28]:
for i in tqdm(range(0,len(missing_cats))):
    sequence=missing_cats["description"][i]
    predicted_cats+=[generate_predictions(sequence,fiction_categories)]
    isbns+=[missing_cats["isbn13"][i]]

100%|██████████| 1695/1695 [02:59<00:00,  9.47it/s]

In [29]:
missing_predicted_df=pd.DataFrame({"isbn13": isbns, "predicted_categories": predicted_cats})

In [30]:
missing_predicted_df

             isbn13 predicted_categories
0     9780002261982              fiction
1     9780006280897           nonfiction
2     9780006280934           nonfiction
3     9780006380832           nonfiction
4     9780006470229              fiction
...             ...                  ...
1690  9788171565641              fiction
1691  9788172235222           nonfiction
1692  9788173031014           nonfiction
1693  9788179921623              fiction
1694  9788185300535           nonfiction

[1695 rows x 2 columns]

In [35]:
books["categories"].unique()

array(['Fiction', 'Detective and mystery stories', 'Christian life',
       'Africa, East', 'Hyland, Morn (Fictitious character)',
       'Adventure stories', 'Arthurian romances', 'Fantasy fiction', nan,
       'English drama', 'Country life', 'English fiction', 'Clergy',
       'Aubrey, Jack (Fictitious character)',
       'Detective and mystery stories, English', 'Black Death',
       'Human cloning', 'Science fiction', 'Great Britain',
       'American fiction', 'American essays', 'Capitalism', 'Ireland',
       'Juvenile Fiction', 'Literary Collections',
       'Beresford, Tommy (Fictitious character)',
       'Imaginary wars and battles', 'Dysfunctional families',
       'Poirot, Hercule (Fictitious character)', 'Christmas stories',
       'Marple, Jane (Fictitious character)', 'Belgians',
       'Baggins, Frodo (Fictitious character)', 'Cambridge (Mass.)',
       'Business enterprises', 'Emotional problems',
       'Characters and characteristics in motion pictures',
       'Fantasy fiction, English', 'Fairy tales, English', 'Parenthood',
       'FICTION', 'Biography & Autobiography', 'Vietnam War, 1961-1975',
       'Computer programmers', 'Actors', 'Friendship', 'Authors',
       'Costume', 'Conduct of life', 'Alienation (Social psychology)',
       'Christianity', 'Language Arts & Disciplines', 'Grandmothers',
       'History', 'Business & Economics', 'Literary Criticism', 'Science',
       'Juvenile Nonfiction', 'African Americans in radio broadcasting',
       'Philosophy', 'Family & Relationships', 'Poetry', 'Self-Help',
       'Sports & Recreation', 'True Crime', 'Psychology', 'Religion',
       'Travel', 'Social Science', 'Health & Fitness', 'Music',
       'Comics & Graphic Novels', 'Medical', 'Body, Mind & Spirit',
       'Education', 'Political Science', 'Antiques & Collectibles',
       'Reference', 'Young Adult Fiction', 'Humor', 'Nature',
       'Foreign Language Study', 'Computers', 'Cosmology', 'Physicists',
       'Australian fiction', 'Australia', 'Families', 'Azerbaijan',
       'Dublin (Ireland)', 'Americans', 'Slave insurrections',
       'Amis, Kingsley', 'Dangerously mentally ill',
       'American literature', 'Life on other planets', 'Anger', 'Comedy',
       "Alzheimer's disease", 'College teachers', 'China', 'Essays',
       'Mothers and sons', 'Atonement', 'Badgers', 'Gangs',
       'Human behavior', 'Social action', 'Horror',
       'Galicia (Spain : Region)', 'Businesswomen', 'Domestic fiction',
       'Japan', 'Crime investigation', 'Authors, German',
       'Short stories, American', 'Short stories', 'African Americans',
       'Exorcism', 'Europe', 'Horror tales', 'Cults', 'Divorced women',
       'Bracelets', 'Death', 'Egyptologists', 'Demonology', 'Alcoholics',
       'Feature films [DVD]', 'England', 'Adultery', 'Accidents',
       'Christmas', 'World War, 1914-1918', 'Authors, English',
       'College attendance', 'London (England)', 'Children of the rich',
       'Literature', 'City and town life', 'Classical fiction', 'War',
       'Historical fiction', 'Igbo (African people)', 'Law',
       'Mathematics', 'Art', 'Ghost stories, American', 'Pigeons',
       'Electrons', 'Existential psychotherapy', 'Albigenses', 'Sex',
       'Tobruk, Battles of, 1941-1942', 'Latin America', 'Drama',
       'Confucianism', 'Performing Arts', 'BIOGRAPHY & AUTOBIOGRAPHY',
       'British', 'English', 'Humorous stories, English',
       'Authors, Italian', 'Canadian wit and humor', 'Obesity',
       'High schools', 'English poetry', 'Amour - Ouvrages avant 1800',
       'Candy', 'Dracula, Count (Fictitious character)',
       'Bond, James (Fictitious character)', 'Dead',
       'Cabrillo, Juan (Fictitious character)', 'Cookery', 'Jews',
       'Children of Holocaust survivors', 'American wit and humor',
       'Experimental fiction, American', 'Argentine literature',
       'Novelists, American', 'Brothers', 'Men', 'Czechoslovakia',
       'French drama', 'Epidemics', 'Repression (Psychology)',
       'Horror tales, American', 'Mentally ill', 'Handicapped youth',
       'Sea monsters', 'Adirondack Mountains (N.Y.)', 'Design',
       'Adult children', 'Folklore', 'Pets', 'Authors, American',
       'Experimental fiction', "Children's stories", 'Agriculture',
       'First loves', 'Cancer', 'Curiosities and wonders',
       'Graphic novels', 'Erinyes (Greek mythology)',
       'Greek drama (Tragedy)', 'Babytime resource',
       'Little, Stuart (Fictitious character)', 'Fantasy',
       'Zero (The number)', 'Psychoanalysis and religion',
       'Poets, Chilean', 'Photography', 'Cooking', 'Art museum curators',
       'Bibles', 'Literary Criticism & Collections', 'Authors, Canadian',
       'Air pilots', 'Community life', 'Rock musicians',
       'Brothers and sisters', 'Conspiracies', 'Egypt', 'Diary fiction',
       'Bail bond agents', 'Catholics', 'Political leadership',
       'Bosnia and Hercegovina', 'Mormon fundamentalism',
       'American Wit And Humour', 'Cocaine industry', 'Murder', 'India',
       'Bombings', 'Autonomy (Psychology).',
       'Dent, Arthur (Fictitious character)', 'Paris (France)',
       'Antislavery movements', 'Books', 'Apartments', 'Actresses',
       'Germany', 'Animal sanctuaries', 'Adventure fiction', 'Buddhism',
       'Bereavement', 'Human-alien encounters', 'Motion picture plays',
       'Amnesia', 'Auschwitz (Poland : Concentration camp)',
       'Cities and towns', 'Political fiction', 'History, Modern',
       'Antisemitism', 'Popular culture', 'Misogyny', 'Apartheid',
       'Botswana', 'France', 'Gardening', 'American poetry',
       'Cooking, French', 'Occult fiction', 'Architecture', 'Bible',
       'Caterpillars', 'Ryan, Jack (Fictitious character)',
       'Intelligence service', 'Arctic regions',
       'Lecter, Hannibal (Fictitious character)', 'American drama',
       "Children's plays", 'Animals, Mythical', 'Diaries',
       'Babysitters Club (Imaginary organization)', 'United States',
       'Horror stories', 'Trials (Witchcraft)',
       "Children's poetry, American", 'Ghost stories', 'Stone age',
       'Alanna (Fictitious character : Pierce)',
       "Children's stories, English", 'Queens', 'Los Angeles (Calif.)',
       'Television', 'Bullying', 'Adolescence', 'Fantasy.', 'Boys',
       'Mental illness', 'Allegories', 'Dominican Republic',
       'Games & Activities', 'Blake, Anita (Fictitious character)',
       'Detective and mystery stories, English.',
       'Drenai (Imaginary place)', 'Discworld (Imaginary place)',
       'Persian Gulf War, 1991', 'Fairy tales', 'Criminals',
       'Arabic fiction', 'Chocolate', 'Brewing', 'Ballet dancers',
       'Cider house rules. (Motion picture)', 'Finance, Personal',
       'New York (State)', 'Contests', 'Apprentices', 'Blind',
       'Manuscripts', 'Divorced people', 'Boston (Mass.)',
       'Amazon River Region', 'Airplane crash survival', 'Civil law',
       'Hitchhiking', 'Latin poetry', 'Bus travel', 'Teenagers',
       'Beowulf', 'Gambling', 'Poets, American', 'Czech Republic',
       'Prisoners of war',
       'Englisch - Geschichte - Lyrik - Aufsatzsammlung',
       'Mathematicians', 'Black humor (Literature)', 'Dreams',
       'Apartment houses', 'Boarding schools', 'Short stories, English',
       'Alternative histories (Fiction)', 'Friendship in adolescence',
       'Cowboys', 'Adult education', 'Ballet', 'Family',
       'English language', 'Sexual behavior surveys', 'Espionage',
       'Electronic books', 'Love poetry', 'Alcestis (Greek mythology)',
       'Boarding school-fiction', 'African American men', 'Sex customs',
       'Technology & Engineering', 'Essentialism (Philosophy)',
       'Animal sounds', 'Music trade', 'Computer science', 'Democracy',
       'Psycho (Motion picture : 1960)', 'Business women', 'Angels',
       'Aboriginal Australians', 'Interplanetary voyages',
       'Photographers', 'Labrador retriever', 'Reducing diets',
       'Fantasy fiction, American', 'Archaeological expeditions',
       'Explorers', 'Love', 'Games', 'Birds', 'Language and languages',
       'Blacks', 'City girl', 'Humorous fiction', 'Chick lit',
       'Female friendship', 'Cornwall (England : County)',
       'American wit and humor, Pictorial',
       'Film producers and directors', 'Kyoto (Japan)', 'Aging',
       'Arithmetic', 'Bedtime', 'Man-woman relationships',
       'Confianza en sí mismo', 'Dallas, Eve (Fictitious character)',
       'Novelists, English', 'Escapes', 'Benedictine monasteries',
       'Amyotrophic lateral sclerosis', 'Abused wives', 'Birthparents',
       'Conner, Rainie (Fictitious character)',
       'Continental Op (Fictitious character)', 'Cats',
       '87th Precinct (Imaginary place)', 'Women terrorists',
       'Organized Crime', 'Defectors', 'College stories', 'Austria',
       'Surealism', 'Cellists', 'Holt, Max (Fictitious character)',
       'Magic', 'JUVENILE FICTION', 'Canada', 'Dystopias',
       'Good and evil', 'Heroes', 'Large print books', 'Dragons',
       'Christian saints', 'Insane, Criminal and dangerous', 'Divorce',
       'Study Aids', 'Sea stories',
       'Detective and mystery comic books, strips, etc',
       'Theology, Doctrinal', 'Artists', 'House & Home',
       'Crafts & Hobbies', 'Humorous stories, American', 'Book burning',
       'Nanjing (Jiangsu Sheng, China)', 'Shipwrecks',
       'Comic books, strips, etc', 'Communication in families',
       'Audiobooks', 'Existentialism', 'Autism', 'Botanique',
       'Antiheroes', 'English essays', 'LITERARY CRITICISM', 'Amish',
       'Human-animal relationships', 'Imperialism', 'Aged women',
       'Humorous stories', 'Butlers', 'Gardens', 'Assassins',
       'Married people', 'Crusades', 'Church work with the poor',
       'Estados Unidos - Relaciones exteriores - 1945-1989',
       'Authors, Cuban', 'Death (Fictitious character : Gaiman)',
       'Astronomers', 'Epic literature', 'Girls', 'Elves',
       'Conan (Fictitious character)', 'Otherland (Imaginary place)',
       'Courage', 'Identity (Psychology)', 'Science fiction, American',
       'Mars (Planet)', 'Transportation', 'Bosnia and Herzegovina',
       'Disasters', 'Lisbon (Portugal)', 'Aeronautics', 'Childbirth',
       'Consumer behavior', 'Seduction', 'Authors, Arab',
       'Nineteen ninety-eight, A.D.', 'Animals',
       'Detective and mystery stories, American',
       'Everest, Mount (China and Nepal)', 'Family life',
       'Boats and boating', 'People with social disabilities',
       'Minimal brain dysfunction in children', 'Spiritual life',
       'Meditation', 'Gay men', 'Christian fiction',
       'Napoleonic Wars, 1800-1815', 'Indic fiction (English)'],
      dtype=object)

In [31]:
books=pd.merge(books,missing_predicted_df,on="isbn13", how="left")
books["simple_categories"]=np.where(books["simple_categories"].isna(),books["predicted_categories"],books["simple_categories"])
books=books.drop(columns=["predicted_categories"])

In [32]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,nonfiction
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,0,Journey to the East,9788173031014 This book tells the tale of a ma...,nonfiction
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,nonfiction

In [33]:
books[books["categories"].str.lower().isin([
    "romance",
    "science fiction",
    "scifi",
    "fantasy",
    "horror",
    "mystery",
    "thriller",
    "comedy",
    "crime",
    "historical"
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,missing,title_subtitle,tagged_description,simple_categories
24,9780006513087,0006513085,Gravity,Tess Gerritsen,Science fiction,http://books.google.com/books/content?id=KI66c...,Emma Watson a research physician has been trai...,2004.0,4.04,342.0,8024.0,0,Gravity,9780006513087 Emma Watson a research physician...,nonfiction
475,9780099410355,0099410354,Traitor,Matthew Woodring Stover,Science fiction,http://books.google.com/books/content?id=VbICO...,"From the depths of catastrophe, a glimmer of h...",2002.0,4.00,320.0,6765.0,0,Traitor,"9780099410355 From the depths of catastrophe, ...",nonfiction
478,9780099422341,0099422344,Yeats is Dead!,Joseph O'Connor,Comedy,http://books.google.com/books/content?id=DrE3I...,"In aid of Amnesty International, this is a bri...",2002.0,3.39,298.0,34.0,0,Yeats is Dead!: A Novel by Fifteen Irish Writers,"9780099422341 In aid of Amnesty International,...",fiction
491,9780099446729,0099446723,Blackwood Farm,Anne Rice,Horror,http://books.google.com/books/content?id=cIn8T...,"Lestat Is Back, Saviour And Demon, Presiding O...",2003.0,3.86,774.0,26145.0,0,Blackwood Farm,"9780099446729 Lestat Is Back, Saviour And Demo...",fiction
1090,9780261102422,0261102427,The Silmarillion,John Ronald Reuel Tolkien,Fantasy,http://books.google.com/books/content?id=22ePu...,Tolkien's Silmarillion is the core work of the...,1999.0,3.91,384.0,253.0,0,The Silmarillion,9780261102422 Tolkien's Silmarillion is the co...,fiction
1435,9780340837955,0340837950,Stranger in a Strange Land,Robert A. Heinlein,Science fiction,http://books.google.com/books/content?id=ZQhiP...,"Epic, entertaining, Stranger in a Strange Land...",2005.0,3.92,672.0,563.0,0,Stranger in a Strange Land,"9780340837955 Epic, entertaining, Stranger in ...",fiction
1439,9780345251220,0345251229,Visions from Nowhere,William Arrow,Science fiction,NaN,"The first novel in the series, ""Return to the ...",1976.0,3.23,183.0,10.0,0,Visions from Nowhere,"9780345251220 The first novel in the series, ""...",fiction
2845,9780575075597,0575075597,Replay,Ken Grimwood,Fantasy,http://books.google.com/books/content?id=9vmNP...,At forty-three Jeff Winston is tired of his lo...,2005.0,4.16,272.0,412.0,0,Replay,9780575075597 At forty-three Jeff Winston is t...,nonfiction
2860,9780590254762,0590254766,"The lion, the witch and the wardrobe",Clive Staples Lewis,Fantasy,NaN,Four English school children enter the magic l...,1995.0,4.21,189.0,860.0,0,"The lion, the witch and the wardrobe",9780590254762 Four English school children ent...,nonfiction
3288,9780739423851,0739423851,Wizard's Castle,Diana Wynne Jones,Fantasy,http://books.google.com/books/content?id=hB7hA...,Howl's moving castle - Eldest of three sisters...,2002.0,4.44,376.0,439.0,0,Wizard's Castle,9780739423851 Howl's moving castle - Eldest of...,nonfiction
3289,9780739439708,0739439707,Time Quartet,Madeleine L'Engle,Science fiction,NaN,"Blending magic with quantum physics, Madeleine...",2003.0,4.35,646.0,165.0,0,Time Quartet,9780739439708 Blending magic with quantum phys...,fiction
3563,9780760728505,076072850X,"20,000 Leagues Under the Sea",Jules Verne,Science fiction,NaN,Retells the adventures of a French professor a...,2002.0,3.88,394.0,135778.0,0,"20,000 Leagues Under the Sea",9780760728505 Retells the adventures of a Fren...,fiction
4483,9781416502043,1416502041,The Voyage of the Jerle Shannara Trilogy,Terry Brooks,Fantasy,http://books.google.com/books/content?id=jqVsA...,When the body of a half-drowned elf is found f...,2004.0,4.26,1260.0,84.0,0,The Voyage of the Jerle Shannara Trilogy,9781416502043 When the body of a half-drowned ...,nonfiction
4979,9781841494081,1841494089,The Darkness that Comes Before,R. Scott Bakker,Fantasy,http://books.google.com/books/content?id=BG8qG...,A score of centuries has passed since the Firs...,2005.0,3.79,638.0,317.0,0,The Darkness that Comes Before,9781841494081 A score of centuries has passed ...,nonfiction
5040,9781857231359,185723135X,Use of Weapons,Iain Banks,Science fiction,NaN,The man known as Cheradenine Zakalwe was one o...,1992.0,4.19,411.0,30779.0,0,Use of Weapons,9781857231359 The man known as Cheradenine Zak...,nonfiction
5057,9781857989342,1857989341,The Gods Themselves,Isaac Asimov,Science fiction,http://books.google.com/books/content?id=8ClIP...,"In the year 2100, mankind on Earth, settlers i...",2000.0,4.09,288.0,41304.0,0,The Gods Themselves,"9781857989342 In the year 2100, mankind on Ear...",nonfiction

In [37]:
books.to_csv("/content/drive/MyDrive/uni/Study/book-recommendation/books_with_categories.csv",index=False)